---
- name: minio_install | create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: minio_install | create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    shell: /sbin/nologin

- name: "minio_install | Create the minio directory under minio mount point"
  file:
    path: "{{ minio_mount_path }}/minio"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: minio_install | download minio server
  get_url:
    url: "{{ minio_server_download_url }}"
    dest: "{{ minio_server_bin }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755

- name: minio_install | create systemd service
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: minio_install | enable and start the minio service
  systemd:
    name: minio
    state: started
    enabled: yes
