---
- name: minio_install | create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: minio_install | create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    shell: /sbin/nologin

- name: minio_install | download minio server
  local_action:
    module: get_url
    url: "{{ minio_server_download_url }}"
    dest: /tmp/minio

- name: minio_install | copy the minio server to remote server
  copy:
    src: /tmp/minio
    dest: "{{ minio_server_bin }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755

- name: minio_install | Set permissions for minio folders
  file:
    path: /mnt/{{ inventory_hostname }}
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: minio_install | copy minio default
  template:
    src: minio.j2
    dest: /etc/default/minio

- name: minio_install | create systemd service
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio
