---
- name: minio_ssl | create the ssl directory
  file:
    path: /home/{{ minio_user }}/.minio/certs
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: minio_ssl | copy the ssl private key
  copy:
    src: "{{ ssl_private_key }}"
    dest: "/home/{{ minio_user }}/.minio/certs/private.key"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0600
  notify: restart minio

- name: minio_ssl | copy the ssl certificate
  copy:
    src: "{{ ssl_public_cert }}"
    dest: "/home/{{ minio_user }}/.minio/certs/public.crt"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0600
  notify: restart minio

- name: minio_ssl | Allow non-root user to access/bind the port 443
  command: "setcap CAP_NET_BIND_SERVICE=+ep {{ minio_server_bin }}"

- name: minio_install | enable and start the minio service
  systemd:
    name: minio
    state: started
    enabled: yes
