#Prepare the disk in servers
disk_path: /dev/sdb

# Domain for  nodes
dns_domain: example.com

# minio installation parameters
minio_server_download_url: https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2020-12-12T08-39-07Z
minio_server_bin: /usr/local/bin/minio

# Runtime user and group for the minio server service
minio_user: minio
minio_group: minio

minio_volumes: http://minio-01.example.com:9000/mnt/minio-01 http://minio-02.example.com:9000/mnt/minio-02 http://minio-03.example.com:9000/mnt/minio-03 http://minio-04.example.com:9000/mnt/minio-04

# Minio server listen address
minio_server_addr: ":9000"

# Minio credentials
minio_access_key: Test
minio_secret_key: Test@12345

# Switches to disable minio client installation
skip_client: False

# Minio client mc parameters
minio_client_download_url: https://dl.minio.io/client/mc/release/linux-amd64/mc
minio_client_bin: /usr/local/bin/mc

# SSL keys and certificates
ssl_private_key: minio.key
ssl_public_cert: minio.crt
